### ISSUE TITLE
I upgraded to 1.1.2, but the error is still not fixed.

### ISSUE THREAD

**Issue by acttoz** [natml-hub/movenet#7] opened 2023-02-23 02:41 UTC
The error content is the same as below

**Comment by olokobayusuf** [comment] 2023-02-23 03:41
Looking into this.

**Comment by olokobayusuf** [comment] 2023-02-23 13:31
@acttoz I can't reproduce the crash you are getting. Can you modify your code with the following?
```csharp
var configuration = new MLEdgeModel.Configuration { computeTarget = MLEdgeModel.ComputeTarget.CPU };
var predictor = await MoveNetPredictor.Create(configuration: configuration);
```
Let me know if you still get a crash.

**Comment by acttoz** [comment] 2023-02-23 15:22
It does not works still.

[logcat_natml1.1.2.txt](https://github.com/natml-hub/movenet/files/10815301/logcat_natml1.1.2.txt)

**Comment by acttoz** [comment] 2023-02-23 16:06
I still get a crash.
The log is here.
[app.natsuite.posecam-logcat.txt](https://github.com/natml-hub/movenet/files/10815721/app.natsuite.posecam-logcat.txt)

**Comment by olokobayusuf** [comment] 2023-02-23 17:09
From the logs:
```
Error tflite Division by 0
2023-02-24 01:05:17.735 26096 26147 Error tflite Node number 98 (FLOOR_DIV) failed to invoke.
```
I'm going to investigate why I can't reproduce this on my devices with the exact same model.

**Comment by olokobayusuf** [comment] 2023-02-23 17:16
@acttoz actually I take this back. I've been able to repro!

**Comment by olokobayusuf** [comment] 2023-02-23 22:21
@acttoz FOUND IT 🎊 🍾 🎉 . Thank you so much for reporting this issue! It turns out to be a major issue in the most unexpected way. Fix coming later tonight.

**Comment by ksh1283f** [comment] 2023-02-27 10:10
I got the same issue(Error AndroidRuntime at libNatML.NMLModelPredict(NMLModelPredict)...) on my android device. Please release the fix ASAP 😭😭

**Comment by olokobayusuf** [comment] 2023-02-27 15:56
Dropping in a few hours. Gotta push out a VideoKit update first.

**Comment by olokobayusuf** [comment] 2023-02-28 20:40
This has been fixed in [NatML 1.1.3](https://github.com/natmlx/natml/releases/tag/1.1.3).

**Closed by olokobayusuf** 2023-02-28 20:40 UTC
Labels: android, bug, critical
